language: python

sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
      - curl
      - php5-cli

branches:
  only:
  - '/^test.*/'
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
  - ENV= M="comp builder frontend build sql_storage rstwriter"

install:
- "pip install -r requirements.txt"
- ./build/rebuild-lib-links.sh $HOME/src
- ./build/docutils-checkout.sh
- ./build/nabu-checkout.sh
- ls -la $HOME/src/python-docutils
- ls -la $HOME/src/python-docutils/docutils-svn/
- ls -la $HOME/src/python-docutils/docutils-svn/branches
- ls -la lib/
- ls -la lib/docutils-lossless/
- 'curl -sS https://getcomposer.org/installer | php -- --install-dir=~/.local/bin --filename=composer'
- ~/.local/bin/composer --version

before_script: []

script: 
- coverage run --source=dotmpe test/main.py $M
# sql_storage

# Default travis Python build:
#
#install:
#  - "pip install ."
#  - "pip install -r requirements.txt"
#
#script: nosetests
