language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - curl
      - php5-cli

install:
- . ./tools/ci/install-composer.sh
- test -x "$(which composer)" -a -x "$(which pip)"
- . ./tools/ci/install-deps.sh
- ./build/rebuild-lib-links.sh $HOME/src
- ./build/docutils-checkout.sh
- ./build/nabu-checkout.sh

- ls -la $HOME/src/python-docutils
- ls -la $HOME/src/python-docutils/docutils-svn/
- ls -la $HOME/src/python-docutils/docutils-svn/branches
- ls -la lib/
- ls -la lib/docutils-lossless/

before_script: []

script: 
- echo "Testing modules: $M"
- coverage run --source=dotmpe test/main.py $M || true
- ./vendor/behat/behat/bin/behat
- bats test/*.bats

env:
  global:
    - DEP_PREFIX=$HOME/.local
    - PATH=$PATH:$DEP_PREFIX/bin:$PREFIX/bin
    - PYTHONPATH=$PYTHONPATH:.
  matrix:
  - ENV= M="$(./test/main.sh)"

branches:
  only:
  - master
  - '/^test.*/'
  - '/^dev.*/'
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'
  - '/^features\/.*/'

notifications:
  email:
    on_success: never


# Default travis Python build:
#
#install:
#  - "pip install ."
#  - "pip install -r requirements.txt"
#
#script: nosetests

