language: python

sudo: false

python:
  - "2.6"
#  - "2.7"

branches:
  only:
  - test
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
  - ENV=

script: 
- coverage run --source=dotmpe test/main.py comp builder
# frontend build sql_storage rstwriter

# Default travis Python build:
#
#install:
#  - "pip install ."
#  - "pip install -r requirements.txt"
#
#script: nosetests
