# git-versioning main: docutils-ext-mpe

- type: application/vnd.dotmpe.project
  main: docutils-ext-mpe
  id: docutils-ext-mpe

  version: 0.0.1-dev # docutils-ext-mpe
  environments: [ 'development' ]

  vendor: dotmpe
  distribution: public
  license: GPL-3.0

  scripts:
    check:
      - make stat
      - "./tools/ci/tags.sh *.* doc dotmpe examples features lib log test tools var"
    test:
      - make build test
      - ./tools/rst-form.py examples/form-1.rst
      #- ./tools/rst-form.py var/test-form.1.field-id.rst
      - ./tools/rst-outline.py examples/main.rst
      - python ./tools/rst-definitions.py examples/main.rst
      # FIXME ./tools/mpe-sitefile.py examples/main.rst
      # FIXME ./tools/rst2rst-mpe.py examples/main.rst
      # FIXME ./tools/brx-crm-pub.py
      #- ./tools/rst2latex-brx examples/main.rst
      #- ./tools/rst2pprint-brx examples/main.rst
      #- ./tools/rst2xml-brx examples/main.rst
    build: make build

  pd-meta:
    run:
      check-tags: "./tools/ci/tags.sh:*.*:doc:dotmpe:examples:features:lib:log:test:tools:var"

    check: "make:stat sh:tools/ci/tags.sh:*.*:doc:dotmpe:examples:features:lib:log:test:tools:var :git:status"
    test: "make:test"
    build: ""
    install: "sh:pip:install:."

    tasks:
      tags:
        - TODO # tasks:no-check
        - XXX # tasks:no-check
        - FIXME # tasks:no-check
        - BUG # tasks:no-check
        - NOTE # tasks:no-check

